// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace MvvmStory.Touch.Tests
{
	[Storyboard("TestViewController",Id="SecondViewController")]
	public partial class SecondViewController : UITableViewController
	{
		public SecondViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
