// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace MvvmStory.Touch.Tests
{
	[StoryboardAttribute]
	public partial class TestViewController : UIViewController
	{
		public TestViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
